<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-RO5NS03S" name="Default test" tests="24" failures="1" timestamp="11 Jul 2017 06:07:08 GMT" time="0.181" errors="0">
  <testcase name="checkRegistrationPage" time="0.006" classname="TestersGroupID.TestNGArtifactID.LoginTestWithDataProvider"/>
  <testcase name="correctCredencials" time="0.008" classname="TestersGroupID.TestNGArtifactID.LoginTestWithDataProvider"/>
  <testcase name="correctCredencials" time="0.012" classname="TestersGroupID.TestNGArtifactID.LoginTestWithDataProvider"/>
  <testcase name="correctCredencials" time="0.002" classname="TestersGroupID.TestNGArtifactID.LoginTestWithDataProvider"/>
  <testcase name="correctCredencials" time="0.002" classname="TestersGroupID.TestNGArtifactID.LoginTestWithDataProvider"/>
  <testcase name="correctCredencials" time="0.004" classname="TestersGroupID.TestNGArtifactID.LoginTestWithDataProvider"/>
  <testcase name="correctCredencials" time="0.001" classname="TestersGroupID.TestNGArtifactID.LoginTestWithDataProvider"/>
  <testcase name="wrongCredencials" time="0.002" classname="TestersGroupID.TestNGArtifactID.LoginTestWithDataProvider"/>
  <testcase name="wrongCredencials" time="0.002" classname="TestersGroupID.TestNGArtifactID.LoginTestWithDataProvider"/>
  <testcase name="wrongCredencials" time="0.004" classname="TestersGroupID.TestNGArtifactID.LoginTestWithDataProvider"/>
  <testcase name="wrongCredencials" time="0.002" classname="TestersGroupID.TestNGArtifactID.LoginTestWithDataProvider"/>
  <testcase name="wrongCredencials" time="0.0" classname="TestersGroupID.TestNGArtifactID.LoginTestWithDataProvider"/>
  <testcase name="wrongCredencials" time="0.002" classname="TestersGroupID.TestNGArtifactID.LoginTestWithDataProvider"/>
  <testcase name="loginTestWithCorrectCredencials" time="0.006" classname="TestersGroupID.TestNGArtifactID.LoginTest"/>
  <testcase name="loginTestWithWrongCredencials" time="0.001" classname="TestersGroupID.TestNGArtifactID.LoginTest"/>
  <testcase name="phoneTest2" time="0.002" classname="TestersGroupID.TestNGArtifactID.PriorityAndDependsOn"/>
  <testcase name="emailTest4" time="0.001" classname="TestersGroupID.TestNGArtifactID.PriorityAndDependsOn"/>
  <testcase name="emailTest2" time="0.003" classname="TestersGroupID.TestNGArtifactID.PriorityAndDependsOn">
    <failure type="java.lang.AssertionError" message="expected [John] but found [Solomon]">
      <![CDATA[java.lang.AssertionError: expected [John] but found [Solomon]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at TestersGroupID.TestNGArtifactID.PriorityAndDependsOn.emailTest2(PriorityAndDependsOn.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- emailTest2 -->
  <testcase name="phoneTest3" time="0.0" classname="TestersGroupID.TestNGArtifactID.PriorityAndDependsOn"/>
  <testcase name="phoneTest1" time="0.001" classname="TestersGroupID.TestNGArtifactID.PriorityAndDependsOn"/>
  <testcase name="phoneTest4" time="0.001" classname="TestersGroupID.TestNGArtifactID.PriorityAndDependsOn">
    <skipped/>
  </testcase> <!-- phoneTest4 -->
  <testcase name="emailTest3" time="0.001" classname="TestersGroupID.TestNGArtifactID.PriorityAndDependsOn">
    <skipped/>
  </testcase> <!-- emailTest3 -->
  <testcase name="emailTest1" time="0.0" classname="TestersGroupID.TestNGArtifactID.PriorityAndDependsOn">
    <skipped/>
  </testcase> <!-- emailTest1 -->
  <testcase name="myTestCase" time="0.002" classname="TestersGroupID.TestNGArtifactID.PassingParameter"/>
</testsuite> <!-- Default test -->
